<script setup>
//import RegistrationForm from '../components/RegistrationForm.vue'
//import UserLogin from '../components/UserLogin.vue'
import TodoLis from '../components/TodoLis.vue'
</script>

<template>
  <main>
    <TodoLis></TodoLis> 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
  </main>
</template>
 